
#include <stdio.h>  
#include <absacc.h>
#include <math.h>
#include <absacc.h>
#include <math.h>
#include <stdarg.h>
#include <string.h>



//#define PART_LM3S5739
 //#include "pin_map.h"
 #include "mcudef.h"
 #include "GLOBLE.H"
 #include "macro.h"
 #include "untitled_ah9837.h"
 #include "vector_interrupes.h" 

 #include "sample_I.h"
 #include "debug.h"
 #include "modify.h"
 
 #include "Fre_test.h"




 #include "V_test.h"
 #include "commonView.h"
 #include "R_ad7705.h"
 //#include "Temp_control.h"


 
 //#include "mainHandle.h"
// #include "Oilset.h"
 #include "my_math.h"
// #include "print.h"
// #include "fm31256.h"
// #include "LM3s_I2CM.h"
//#include "ADC_BAT.h"
 //#include "modifyset.h"
 #include "Uart0_hander.h"
// #include "Viewdata.h"
// #include "ch376hft.h" 
// #include "HAL.H"







